name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run
        env:
          CYPRESS_WEATHER_BASE_URL: ${{ secrets.WEATHER_BASE_URL }}
          CYPRESS_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
